#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
struct CalendarDay 
{
    char* dayName;
    int date;
    char* activity;
};
int main() 
{
    struct CalendarDay calendar[7];
    for (int i = 0; i < 7; i++) {
    calendar[i].dayName = (char*)malooc(20);
    calendar[i].activity = (char*)malloc(100); 
    sprintf(calendar[i].dayName, "Day %d", i + 1);
    calendar[i].date = i + 1;
    sprintf(calendar[i].activity, "Activity for Day %d", i + 1);
    }
    for (int i = 0; i < 7; i++) {
    printf("Day Name: %s\n", calendar[i].dayName);
    printf("Date: %d\n", calendar[i].date);
    printf("Activity: %s\n\n", calendar[i].activity);
    }
    for (int i = 0; i < 7; i++) {
        free(calendar[i].dayName);
        free(calendar[i].activity);
    }
    getch();
    return 0;
}
